spring:
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
